// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsrngshpmtkiwcpzqsyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzcm5nc2hwbXRraXdjcHpxc3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTM5NjUsImV4cCI6MjA2NzM4OTk2NX0.5NqKmtmgDnIXaIYvk6j4xB9HaqzSIvBRNSTL_RtjIQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});